### ISSUE TITLE
VSSDK006CheckServicesExistAnalyzer throwing ArgumentException: Syntax node is not within syntax tree

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/VSSDK-Analyzers#102]
#### Bug description

- Version of the vssdk-analyzers: 16.0.29
- Analyzer rule: VSSDK006CheckServicesExistAnalyzer
- Error (exception message, type, and callstack where applicable): 

> Analyzer 'Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'.
> 
> 'Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer' threw the following exception:

```
SyntaxTree: D:\repos\Scalability Measurment\src\VSUtilitiesVSIX\CMDPackage.cs
SyntaxNode: this.GetService(typeof(SDTE)) [InvocationExpressionSyntax]@[4656..4685) (87,31)-(87,60)

System.ArgumentException: Syntax node is not within syntax tree
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer.CompilationState.IsThrowingNullCheck(SyntaxNode node, ISymbol symbol, SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer.CompilationState.IsNonNullCheck(SyntaxNode node, ISymbol symbol, SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer.CompilationState.<>c__DisplayClass6_0.<ScanBlockForDereferencesWithoutNullCheck>b__3(SyntaxNode n)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer.CompilationState.ScanBlockForDereferencesWithoutNullCheck(SyntaxNodeAnalysisContext context, ISymbol symbol, SyntaxNode containingBlockOrExpression)
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer.CompilationState.<>c__DisplayClass5_1.<AnalyzeInvocationExpression>b__15(<>f__AnonymousType2`2 <>h__TransparentIdentifier2)
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.SDK.Analyzers.VSSDK006CheckServicesExistAnalyzer.CompilationState.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

#### To Reproduce
Steps or code to reproduce the behavior:
1. Clone https://devdiv.visualstudio.com/InternalTools/_git/Scalability%20Measurment
2. Rename folder to `Scalability Measurment` (works around an unrelated bug with percent-encoded sequence in folders)
2. Open the solution
2. Install SDK analyzers (a VS SDK VSIX prompted me to do this, which did it automatically)
3. Error list shows above warning

#### Expected behavior
No warning.

**Comment by AArnott** [comment]
Actually fixed by 4a88093b418
