### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by maxperga** [Microsoft/VSSDK-Analyzers#48]
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer' threw an exception of type 'System.Exception' with message 'Analyzer failure while processing syntax at C:\git\WinAnyCode\Package\CommandHandler.cs(829,26): System.ArgumentNullException Value cannot be null.
Parameter name: values. Syntax: ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection))'.	WinAnyCode.Package		1	Active	Analyzer 'Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: WinAnyCode.Package
SyntaxTree: C:\git\WinAnyCode\Package\CommandHandler.cs
SyntaxNode: ServiceProvider.GlobalProvider. ... [InvocationExpressionSyntax]@[35032..35102) (828,25)-(828,95)

```
System.Exception: Analyzer failure while processing syntax at C:\git\WinAnyCode\Package\CommandHandler.cs(829,26): System.ArgumentNullException Value cannot be null.
Parameter name: values. Syntax: ServiceProvider.GlobalProvider.GetService(typeof(IVsMonitorSelection)) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedType.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedMember.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeTypeWithinContext(ITypeSymbol type, ISymbol symbol, SyntaxNodeAnalysisContext context, Location focusDiagnosticOn)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedType.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.CommonInterest.QualifiedMember.ToString()
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeTypeWithinContext(ITypeSymbol type, ISymbol symbol, SyntaxNodeAnalysisContext context, Location focusDiagnosticOn)
   at Microsoft.VisualStudio.Threading.Analyzers.VSTHRD010MainThreadUsageAnalyzer.MethodAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.VisualStudio.Threading.Analyzers.Utils.<>c__DisplayClass0_0.<DebuggableWrapper>b__0(SyntaxNodeAnalysisContext ctxt)
```

This is the block I have starting at line 828:

```cs
        public bool OptionRazzleWindowEnabled
        {
            get
            {
                return _settings.OptionRazzleWindowEnabled;
            }

            set
            {
                _settings.OptionRazzleWindowEnabled = value;
            }
        }
```

About the "_settings", it's defined like: 

```cs
        [Import]
        private IUserSettings _settings;
```

Meanwhile its property is defined in this way:

```cs
        /// <summary>
        /// Property representing the state (enabled/disabled) of the 'Razzle Window' feature.
        /// </summary>
        bool OptionRazzleWindowEnabled
        {
            get;
            set;
        }
```

**Comment by AArnott** [comment]
Thanks for reporting. What version of the analyzers do you have installed?

**Comment by AArnott** [comment]
This issue was moved to Microsoft/vs-threading#242

**Comment by maxperga** [comment]
Sorry for forgetting about it.
I'm using v15.6.56-beta .
